language: python
  
install:
  - pip install "coverage>=4.0,<4.4"
  - pip install codeclimate-test-reporter
  - pip install coveralls
  
jobs:
  include:
  - python: "3.6"
    after_success:
    - coveralls
    - codeclimate-test-reporter
    - bash <(curl -s https://codecov.io/bash)
  - python: "3.7"

script:
  coverage run --source=noteandtag setup.py test