---
swagger: "2.0"
info:
  description: "Note and Tag"
  version: "0.1a1"
  title: "Note and Tag REST API"
basePath: "/api/v1"
tags:
- name: "tags"
  description: "Retrieve tags informations"
tags:
- name: "notes"
  description: "Retrieve notes informations"
schemes:
- "https"
- "http"
components:
  parameters:
    offsetParam:
      in: query
      name: offset
      required: false
      schema:
        type: integer
        minimum: 0
      description: The number of items to skip before starting to collect the result set.
    limitParam:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 50
        default: 20
      description: The numbers of items to return.
    sortByParam:
      in: query
      name: sortBy
      required: false
      schema:
        type: string
      description: Sort the items by fields.
paths:
  /tags:
    get:
      description: "Get all tags."
      tags:
      - tags
      parameters:
      - $ref: '#/components/parameters/offsetParam'
      - $ref: '#/components/parameters/limitParam'
      - $ref: '#/components/parameters/sortByParam'
      produces:
      - text/json
      responses:
        "200":
            description: successful operation. Return tags
  /notes:
    get:
      description: "Get all notes."
      tags:
      - notes
      parameters:
      - name: "ids"
        in: "query"
        description: "Return only notes with those ids."
        required: false
        type: "list"
      - name: "label"
        in: "query"
        description: "Return only notes matching this label."
        required: false
        type: "string"
      - name: "body"
        in: "query"
        description: "Return only notes matching this body."
        required: false
        type: "string"
      - name: "tags"
        in: "query"
        description: "Return only notes having those tags."
        required: false
        type: "list"
      - $ref: '#/components/parameters/offsetParam'
      - $ref: '#/components/parameters/limitParam'
      - $ref: '#/components/parameters/sortByParam'
      produces:
      - text/json
      responses:
        "200":
            description: successful operation. Return notes informations
  /notes/{id}:
    get:
      description: "Get a note by id."
      tags:
      - notes
      produces:
      - text/json
      parameters:
      - name: "id"
        in: "path"
        default: "1"
        description: "list of tags"
        required: true
        type: "int"
      responses:
        "200":
            description: successful operation. Return note informations
